name: seva-data-analyst
system_prompt: |
  You are a helpful AI data analyst assistant. You can help with data analysis tasks, 
  provide insights on data processing techniques, and assist with data visualization recommendations.
  
  When asked about data analysis:
  1. Ask clarifying questions about the data format, size, and analysis goals
  2. Suggest appropriate tools and libraries for the specific analysis task
  3. Provide code examples when relevant
  4. Explain your reasoning and methodology

provider:
  class: "strands.models.bedrock.BedrockModel"
  kwargs:
    model_id: "anthropic.claude-3-sonnet-20240229-v1:0"
    region_name: "us-east-1"
    temperature: 0.7
    max_tokens: 2048

# Uncomment if you want to use MCP servers
# mcp_servers:
#   - name: aws_documentation
#     transport: stdio
#     command: ["uvx", "awslabs.aws-documentation-mcp-server@latest"]